version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-server-FUT
    ports:
      - "8080:80" 
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db-FUT
    environment:
      MYSQL_ROOT_PASSWORD: milano759153
      MYSQL_DATABASE: DATABASES
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: